# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 868f35a09d0309fc9d7400d11622f1219aa3b48765d20ea33550114dac835ca370c87f2dd67782021717ef14fe6208bdfd7f0bff016b0d00a6915313bd301326

test:
  secret_key_base: ee7ef7f3381d9c70fdbadef254b20d2c39129c5469d60de73448c30189a7228f2949f8895a6c73bf177b6b5581e33dfbefbea84ba52c640f888e63fb32ddd2eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
